id: IFCA114D8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T19:01:22+00:00'
last_modified: '2022-06-07T12:07:13.509703+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9819
  title: ཟབ་དོན་ཐུགས་ཀྱི་སྙིང་པོ་བདུད་ཀྱི་གཅོད་ཡུལ་གྱི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5054':
      image_group_id: I1KG9821
      title: Volume 1 of zab don thugs kyi snying po bdud kyi gcod yul gyi skor/
      total_pages: 554
      order: 1
      base_file: 5054.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
